import '../models/course.dart';

class ApiService {
  static Future<List<Course>> getCourses() async {
    await Future.delayed(Duration(seconds: 2)); // Simulate network delay

    // Expanded dummy data for testing
    return [
      // Existing courses
      Course(
        title: 'Flutter Basics',
        description: 'Learn the basics of Flutter development. Ideal for beginners.',
        category: 'Development',
        duration: '4 weeks',
        instructor: 'John Doe',
        rating: 4.5,
        imageUrl: 'https://via.placeholder.com/150',
        domain: 'Mobile Development',
        importance: 'Essential',
        weeks: 4,
      ),
      Course(
        title: 'Advanced Flutter',
        description: 'Dive deeper into advanced Flutter concepts. Perfect for experienced developers.',
        category: 'Development',
        duration: '6 weeks',
        instructor: 'Jane Smith',
        rating: 4.7,
        imageUrl: 'https://via.placeholder.com/150',
        domain: 'Mobile Development',
        importance: 'Advanced',
        weeks: 6,
      ),
      Course(
        title: 'UI/UX Design',
        description: 'Learn UI/UX design principles for mobile apps to enhance user experience.',
        category: 'Design',
        duration: '5 weeks',
        instructor: 'Emily Johnson',
        rating: 4.8,
        imageUrl: 'https://via.placeholder.com/150',
        domain: 'Design',
        importance: 'Important',
        weeks: 5,
      ),
      Course(
        title: 'Introduction to Dart',
        description: 'Get started with Dart programming language. Essential for Flutter development.',
        category: 'Programming',
        duration: '3 weeks',
        instructor: 'Michael Brown',
        rating: 4.3,
        imageUrl: 'https://via.placeholder.com/150',
        domain: 'Programming',
        importance: 'Essential',
        weeks: 3,
      ),
      Course(
        title: 'State Management in Flutter',
        description: 'Understand state management techniques and best practices in Flutter.',
        category: 'Development',
        duration: '4 weeks',
        instructor: 'Sara Wilson',
        rating: 4.6,
        imageUrl: 'https://via.placeholder.com/150',
        domain: 'Mobile Development',
        importance: 'Advanced',
        weeks: 4,
      ),
      Course(
        title: 'Effective App Testing',
        description: 'Learn how to test your Flutter applications to ensure quality and performance.',
        category: 'Testing',
        duration: '3 weeks',
        instructor: 'David Lee',
        rating: 4.4,
        imageUrl: 'https://via.placeholder.com/150',
        domain: 'Testing',
        importance: 'Important',
        weeks: 3,
      ),
      // New courses
      Course(
        title: 'Introduction to Cybersecurity',
        description: 'Basics of cybersecurity, including threats and protection methods.',
        category: 'Security',
        duration: '4 weeks',
        instructor: 'Alice Cooper',
        rating: 4.6,
        imageUrl: 'https://via.placeholder.com/150',
        domain: 'Security',
        importance: 'Essential',
        weeks: 4,
      ),
      Course(
        title: 'Data Science with Python',
        description: 'Learn data science techniques and tools using Python.',
        category: 'Data Science',
        duration: '8 weeks',
        instructor: 'Robert Johnson',
        rating: 4.7,
        imageUrl: 'https://via.placeholder.com/150',
        domain: 'Data Science',
        importance: 'Advanced',
        weeks: 8,
      ),
      Course(
        title: 'Machine Learning Essentials',
        description: 'Fundamentals of machine learning algorithms and applications.',
        category: 'Machine Learning',
        duration: '6 weeks',
        instructor: 'Laura White',
        rating: 4.8,
        imageUrl: 'https://via.placeholder.com/150',
        domain: 'Machine Learning',
        importance: 'Important',
        weeks: 6,
      ),
      Course(
        title: 'Web Development with JavaScript',
        description: 'Build dynamic and interactive websites using JavaScript.',
        category: 'Web Development',
        duration: '5 weeks',
        instructor: 'James Smith',
        rating: 4.5,
        imageUrl: 'https://via.placeholder.com/150',
        domain: 'Web Development',
        importance: 'Essential',
        weeks: 5,
      ),
      Course(
        title: 'Cloud Computing Basics',
        description: 'Introduction to cloud computing concepts and services.',
        category: 'Cloud Computing',
        duration: '4 weeks',
        instructor: 'Nancy Adams',
        rating: 4.4,
        imageUrl: 'https://via.placeholder.com/150',
        domain: 'Cloud Computing',
        importance: 'Important',
        weeks: 4,
      ),
      Course(
        title: 'Database Management Systems',
        description: 'Understand the principles and applications of database management systems.',
        category: 'Database',
        duration: '6 weeks',
        instructor: 'Steven Wilson',
        rating: 4.6,
        imageUrl: 'https://via.placeholder.com/150',
        domain: 'Database',
        importance: 'Advanced',
        weeks: 6,
      ),
      Course(
        title: 'Introduction to Artificial Intelligence',
        description: 'Learn the fundamentals of AI, including its applications and ethical considerations.',
        category: 'Artificial Intelligence',
        duration: '5 weeks',
        instructor: 'Emily Clark',
        rating: 4.7,
        imageUrl: 'https://via.placeholder.com/150',
        domain: 'Artificial Intelligence',
        importance: 'Essential',
        weeks: 5,
      ),
      Course(
        title: 'Ethical Hacking and Penetration Testing',
        description: 'Understand ethical hacking practices and how to test systems for vulnerabilities.',
        category: 'Security',
        duration: '6 weeks',
        instructor: 'Robert Davis',
        rating: 4.8,
        imageUrl: 'https://via.placeholder.com/150',
        domain: 'Security',
        importance: 'Advanced',
        weeks: 6,
      ),
      Course(
        title: 'Blockchain Technology and Applications',
        description: 'Explore the principles of blockchain technology and its real-world applications.',
        category: 'Blockchain',
        duration: '5 weeks',
        instructor: 'Lisa Brown',
        rating: 4.6,
        imageUrl: 'https://via.placeholder.com/150',
        domain: 'Blockchain',
        importance: 'Important',
        weeks: 5,
      ),
      Course(
        title: 'Network Fundamentals',
        description: 'Learn the basics of networking, including protocols, topologies, and security.',
        category: 'Networking',
        duration: '4 weeks',
        instructor: 'John Wilson',
        rating: 4.5,
        imageUrl: 'https://via.placeholder.com/150',
        domain: 'Networking',
        importance: 'Essential',
        weeks: 4,
      ),
      Course(
        title: 'Software Development Life Cycle (SDLC)',
        description: 'Understand the phases and methodologies of the software development life cycle.',
        category: 'Software Engineering',
        duration: '4 weeks',
        instructor: 'Mary Johnson',
        rating: 4.4,
        imageUrl: 'https://via.placeholder.com/150',
        domain: 'Software Engineering',
        importance: 'Important',
        weeks: 4,
      ),
      Course(
        title: 'Advanced SQL for Data Analysis',
        description: 'Master advanced SQL techniques for efficient data querying and analysis.',
        category: 'Database',
        duration: '5 weeks',
        instructor: 'Paul Smith',
        rating: 4.7,
        imageUrl: 'https://via.placeholder.com/150',
        domain: 'Database',
        importance: 'Advanced',
        weeks: 5,
      ),
      Course(
        title: 'Virtual Reality Development',
        description: 'Learn how to create immersive experiences using virtual reality technologies.',
        category: 'Virtual Reality',
        duration: '6 weeks',
        instructor: 'Anna Lee',
        rating: 4.8,
        imageUrl: 'https://via.placeholder.com/150',
        domain: 'Virtual Reality',
        importance: 'Advanced',
        weeks: 6,
      ),
      Course(
        title: 'Introduction to Algorithms',
        description: 'Fundamentals of algorithms and data structures for problem-solving.',
        category: 'Algorithms',
        duration: '6 weeks',
        instructor: 'Henry Ford',
        rating: 4.7,
        imageUrl: 'https://via.placeholder.com/150',
        domain: 'Algorithms',
        importance: 'Important',
        weeks: 6,
      ),
      Course(
        title: 'Software Testing and Quality Assurance',
        description: 'Learn techniques for ensuring software quality and reliability through testing.',
        category: 'Testing',
        duration: '5 weeks',
        instructor: 'Rachel Green',
        rating: 4.6,
        imageUrl: 'https://via.placeholder.com/150',
        domain: 'Testing',
        importance: 'Advanced',
        weeks: 5,
      ),
      Course(
        title: 'Introduction to Operating Systems',
        description: 'Understand the core concepts and functionalities of operating systems.',
        category: 'Operating Systems',
        duration: '5 weeks',
        instructor: 'Chris Evans',
        rating: 4.5,
        imageUrl: 'https://via.placeholder.com/150',
        domain: 'Operating Systems',
        importance: 'Important',
        weeks: 5,
      ),
      Course(
        title: 'Developing Mobile Applications with React Native',
        description: 'Learn to build mobile applications using React Native framework.',
        category: 'Mobile Development',
        duration: '6 weeks',
        instructor: 'Natalie Portman',
        rating: 4.7,
        imageUrl: 'https://via.placeholder.com/150',
        domain: 'Mobile Development',
        importance: 'Advanced',
        weeks: 6,
      ),
      Course(
        title: 'Ethics in Technology',
        description: 'Explore the ethical implications and responsibilities of technology professionals.',
        category: 'Ethics',
        duration: '4 weeks',
        instructor: 'Samuel L. Jackson',
        rating: 4.6,
        imageUrl: 'https://via.placeholder.com/150',
        domain: 'Ethics',
        importance: 'Essential',
        weeks: 4,
      ),
      Course(
        title: 'Advanced Web Development',
        description: 'Deep dive into advanced web development techniques and frameworks.',
        category: 'Web Development',
        duration: '7 weeks',
        instructor: 'Mia Farrow',
        rating: 4.8,
        imageUrl: 'https://via.placeholder.com/150',
        domain: 'Web Development',
        importance: 'Advanced',
        weeks: 7,
      ),
      Course(
        title: 'Introduction to Cloud Security',
        description: 'Learn about security practices and risks in cloud computing environments.',
        category: 'Cloud Security',
        duration: '5 weeks',
        instructor: 'Jared Leto',
        rating: 4.5,
        imageUrl: 'https://via.placeholder.com/150',
        domain: 'Cloud Security',
        importance: 'Important',
        weeks: 5,
      ),
      Course(
        title: 'Introduction to DevOps',
        description: 'Understand the principles and practices of DevOps for continuous integration and delivery.',
        category: 'DevOps',
        duration: '6 weeks',
        instructor: 'Sofia Vergara',
        rating: 4.6,
        imageUrl: 'https://via.placeholder.com/150',
        domain: 'DevOps',
        importance: 'Advanced',
        weeks: 6,
      ),
      Course(
        title: 'Big Data Technologies',
        description: 'Explore big data tools and technologies for handling large datasets.',
        category: 'Big Data',
        duration: '7 weeks',
        instructor: 'Ryan Reynolds',
        rating: 4.7,
        imageUrl: 'https://via.placeholder.com/150',
        domain: 'Big Data',
        importance: 'Advanced',
        weeks: 7,
      ),
      Course(
        title: 'Introduction to Game Development',
        description: 'Learn the basics of game development including design principles and tools.',
        category: 'Game Development',
        duration: '5 weeks',
        instructor: 'Zendaya',
        rating: 4.8,
        imageUrl: 'https://via.placeholder.com/150',
        domain: 'Game Development',
        importance: 'Important',
        weeks: 5,
      ),
    ];
  }
}
